### PR TITLE
Python bindings - scaffolding & Travis stuff

### PR DESCRIPTION
**Pull request by slayoo**

### CODE REVIEW

**Comment by tvatter** [comment]
Do you seriously want me to merge a branch which is failing? Don't you eventually want to solve the problems first?

**Comment by tnagler** [comment]
I redirected the PR to a new branch, so it can fail :)

**Comment by slayoo** [comment]
no, no! That's why I wrote "work in progress" in the title - I was just testing git settings with travis

**Comment by slayoo** [comment]
Guys, could you have a look at the ASAN-reported errors in test_bicop_select: https://travis-ci.org/tvatter/vinecopulib/builds/196939374#L7384
Thanks,
S.

**Comment by slayoo** [comment]
@tvatter, @tnagler - OK, Travis seems happy now - could you have a look? As of now, the changes aim only at providing a skeleton for the bindings - nothing is actually exposed and usabel yet besides checking the git_revision of the C++ code from within python.

**Comment by slayoo** [comment]
Thanks. As of now "make test" runs only the one single Python test. The test fails with ASAN=ON due to leaks reported within the Python interpretter.

**Comment by slayoo** [comment]
So ideally, I would suggest to aim at:
```
- cmake -DASAN=ON
- cd tests/allbutpython
- make all test
- cd ../..
- cmake -DASAN=OFF
- cd tests/pythonstuff
- make all test
```
(of course "allbutpython" and "pythonstuff" are just dummy names)

**Comment by tnagler** [comment]
Sounds good.

**Comment by slayoo** [comment]
will resolve the conflict in a moment...

**Comment by slayoo** [comment]
Why is Travis not firing a build?

**Comment by slayoo** [comment]
adding an empty appveyor file helped!

**Comment by slayoo** [comment]
the Appveyor failures can be ignored here - that's just an empty file there (which is there to allow Travis to trigger the builds)

**Comment by slayoo** [comment]
@tvatter, @tnagler This one seems to be ready - build problems on OSX fixed, Appveyor failure should be ignored (there is just an empty appveyor.yml file in this branch)

**Comment by slayoo** [comment]
closing to first resolve the conflict and make the Python stuff compatible with Appveyor

**Comment by slayoo** [comment]
reopening!

**Comment by slayoo** [comment]
@tvatter, @tnagler the changes do include quite some TODOs, but still I would consider it ready for merging - the "hello world" Python test passes on Linux, OSX and Windows

**Comment by tnagler** [comment]
Looks OK to me, but I'd like to keep this branch separate from `master` for a little longer as it doubles the check times on travis.  Any objections to rerouting this to the `python-bindings` branch?

**Comment by slayoo** [comment]
The check times on travis are affected due to the Ubuntu update I guess (needed to get new Boost) - this is not doubling per se - rather adding a constant offset of a few minutes. Is it really an issue? Keeping the .travis.yml, appveyor.yml and CMake files in sync between the branches will likely be cumbersome.

**Comment by slayoo** [comment]
(the total time reported by Travis increased significantly due to one more build being done (Python 3.5 + Python 2.7). Note that the three builds run concurrently, hence the actual wall time differs only by ca. 5-10 minutes.

**Comment by tnagler** [comment]
You're right, I'll merge.

**Comment by slayoo** [comment]
Thanks!

**Comment by tnagler** [comment]
Could you briefly summarize everything what's new in a few bullet points? (for the merge commit msg)

**Comment by slayoo** [comment]
Here it is:
- bindings/python & tests/bindings/python - scaffolding for Python bindings using Boost.Python + first unit test (git_revision)
- CMake:
  - generating include/git_revision.h file
  - enabling CTest tests (as of now used only for Python stuff)
  - findNLOpt - handling WIN32
- Travis:
  - bumping the distro to zesty to get access to Boost 1.63 (for NumPy support)
  - stopping build in case R install.packages fails (through withCallingHandlers())
  - running two concurrent Travis builds for Python 2.7 and Python 3.5
- Appveyor:
  - switching to 32bit mode for compatibility with pre-installed library versions

Sorry for such a big chunk of changes in one PR - the reason (excuse) is that most of those things are somehow related with the Python stuff

**Comment by tnagler** [comment]
Don't worry about the big PR, I prefer related changes to be bundled rather than spread out over several days.

**Pull request merged**
